// SPDX-FileCopyrightText: 2026 CJ van Soest
// SPDX-License-Identifier: MIT
//
// Special-character table for the F5 ("blue cloud") picker, frequency-ordered
// into a 4-column x 10-row grid (German umlauts first, then Nordic, Romance and
// punctuation). Generated by scripts/gen_special_table.py; edit the script, not
// this data. All entries live in Latin-1 Supplement except EURO/EN-DASH/EM-DASH.

#include "special_table.h"

const emoji_entry_t SPECIAL_SET[SPECIAL_COUNT] = {
    {0x00E4, "\xC3\xA4", 2},      // a-umlaut
    {0x00F6, "\xC3\xB6", 2},      // o-umlaut
    {0x00FC, "\xC3\xBC", 2},      // u-umlaut
    {0x00DF, "\xC3\x9F", 2},      // sharp-s
    {0x00C4, "\xC3\x84", 2},      // A-umlaut
    {0x00D6, "\xC3\x96", 2},      // O-umlaut
    {0x00DC, "\xC3\x9C", 2},      // U-umlaut
    {0x00B0, "\xC2\xB0", 2},      // degree
    {0x20AC, "\xE2\x82\xAC", 3},  // euro
    {0x00A7, "\xC2\xA7", 2},      // section
    {0x00B5, "\xC2\xB5", 2},      // micro
    {0x00F1, "\xC3\xB1", 2},      // n-tilde
    {0x00E9, "\xC3\xA9", 2},      // e-acute
    {0x00E8, "\xC3\xA8", 2},      // e-grave
    {0x00EA, "\xC3\xAA", 2},      // e-circ
    {0x00EB, "\xC3\xAB", 2},      // e-diaer
    {0x00E0, "\xC3\xA0", 2},      // a-grave
    {0x00E2, "\xC3\xA2", 2},      // a-circ
    {0x00E1, "\xC3\xA1", 2},      // a-acute
    {0x00E7, "\xC3\xA7", 2},      // c-cedilla
    {0x00EE, "\xC3\xAE", 2},      // i-circ
    {0x00EF, "\xC3\xAF", 2},      // i-diaer
    {0x00ED, "\xC3\xAD", 2},      // i-acute
    {0x00F4, "\xC3\xB4", 2},      // o-circ
    {0x00FB, "\xC3\xBB", 2},      // u-circ
    {0x00F9, "\xC3\xB9", 2},      // u-grave
    {0x00FA, "\xC3\xBA", 2},      // u-acute
    {0x00F3, "\xC3\xB3", 2},      // o-acute
    {0x00E5, "\xC3\xA5", 2},      // a-ring
    {0x00C5, "\xC3\x85", 2},      // A-ring
    {0x00E6, "\xC3\xA6", 2},      // ae
    {0x00C6, "\xC3\x86", 2},      // AE
    {0x00F8, "\xC3\xB8", 2},      // o-slash
    {0x00D8, "\xC3\x98", 2},      // O-slash
    {0x00BF, "\xC2\xBF", 2},      // inv-question
    {0x00A1, "\xC2\xA1", 2},      // inv-exclaim
    {0x00AB, "\xC2\xAB", 2},      // laquo
    {0x00BB, "\xC2\xBB", 2},      // raquo
    {0x2013, "\xE2\x80\x93", 3},  // en-dash
    {0x2014, "\xE2\x80\x94", 3},  // em-dash
};

bool special_font_covers(uint32_t cp) {
    if (cp >= 0x20 && cp <= 0x7F) return true;      // ASCII
    if (cp >= 0xA0 && cp <= 0xFF) return true;      // Latin-1 Supplement
    if (cp == 0x2013 || cp == 0x2014) return true;  // en / em dash
    if (cp == 0x2022) return true;                  // bullet
    if (cp == 0x20AC) return true;                  // euro sign
    return false;
}
