#!/usr/bin/env bash
# Regenerate the extended Montserrat display fonts that cover Western/Central
# European Latin text (umlauts, accents, °, €, guillemets, dashes) so received
# messages and the F5 special-character picker render real glyphs instead of
# the missing-glyph box.
#
# The stock LVGL built-in Montserrat faces only cover ASCII + ° + •, so we ship
# our own extended faces (lv_font_montserrat_<sz>_ext) generated from the same
# Montserrat-Medium.ttf that LVGL bundles.
#
# Requires Node's lv_font_conv (https://github.com/lvgl/lv_font_conv). The NAS
# CI image (espressif/idf:v5.5.1-node) has Node; run there or anywhere with npm:
#
#     scripts/gen_ext_fonts.sh
#
# Output: components/mc_fonts/lv_font_montserrat_<sz>_ext.c  (checked in as
# generated asset data, like emoji_bitmaps.c — do not hand-edit).
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
ttf="$here/managed_components/lvgl__lvgl/scripts/built_in_font/Montserrat-Medium.ttf"
out="$here/components/mc_fonts"
mkdir -p "$out"

# Sizes must match mc_font() in components/mc_ui/lvgl_ui.c.
sizes=(14 16 20 22 24)

# Glyph coverage:
#   0x20-0x7F   ASCII
#   0xA0-0xFF   Latin-1 Supplement (umlauts, accents, °, §, µ, ¿, ¡, «, », ß, æ, ø …)
#   0x2013-0x2014  en/em dash
#   0x2022      bullet (kept from the stock face)
#   0x20AC      euro sign
ranges=(--range 0x20-0x7F --range 0xA0-0xFF --range 0x2013-0x2014 --range 0x2022 --range 0x20AC)

conv() { npx --yes lv_font_conv "$@"; }

for sz in "${sizes[@]}"; do
    f="$out/lv_font_montserrat_${sz}_ext.c"
    echo "generating $(basename "$f")"
    # --no-compress is REQUIRED: the firmware builds with
    # CONFIG_LV_USE_FONT_COMPRESSED=n, so a compressed font (bitmap_format=1)
    # renders as blank glyphs — every label disappears. Plain bitmaps match the
    # stock built-in faces (bitmap_format=0).
    conv \
        --font "$ttf" \
        --size "$sz" \
        --bpp 4 \
        --format lvgl \
        --no-compress \
        --lv-include lvgl.h \
        "${ranges[@]}" \
        --force-fast-kern-format \
        -o "$f"
    # The structure gate (tests/lint/check-structure.sh) requires an SPDX header
    # on every first-party source file; prepend one so regeneration stays green.
    hdr="$(printf '// SPDX-FileCopyrightText: 2026 CJ van Soest\n// SPDX-License-Identifier: MIT\n//\n// Extended Montserrat %spx face (generated by lv_font_conv from\n// Montserrat-Medium.ttf, SIL OFL 1.1). Covers ASCII + Latin-1 Supplement +\n// euro + en/em dash. Do not hand-edit; regenerate via scripts/gen_ext_fonts.sh.\n\n' "$sz")"
    printf '%s' "$hdr" | cat - "$f" > "$f.tmp" && mv "$f.tmp" "$f"
done

echo "done — remember to wire mc_font() and register components/mc_fonts in CMake"
echo "(see docs/features/Special-Characters.md)"
